name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f Dockerfile -t ${{secrets.AZURE_CONTAINERREG_URL}}/my-keyvalue-db:latest .
    - name: Push the Docker image
      run: |
        docker login -u ${{secrets.AZURE_CONTAINERREG_USER}} -p ${{secrets.AZURE_CONTAINERREG_PASS}} ${{secrets.AZURE_CONTAINERREG_URL}}
        docker push ${{secrets.AZURE_CONTAINERREG_URL}}/my-keyvalue-db:latest
